### ISSUE TITLE
Contentに謎の間ができる問題

### ISSUE THREAD

**Issue by FirstStar** [tsuruclient/tsuru#11]
こんな風に謎の間ができることがある なんだろうねこれ よくわかんないや
![screenshot 474](https://user-images.githubusercontent.com/5967271/34903078-d522e66e-f86c-11e7-91ba-5c7ce283b655.jpg)

**Comment by a-happin** [comment]
情報提供です。
リツイートしたすべてのツイートにmin-height: 60px;が適用されているっぽいので短いツイートをRTすると再現します。

**Comment by FirstStar** [comment]
設定されていました とりあえず削除して様子を見てみます

**Comment by FirstStar** [comment]
どうしてこんな設定をしたのか何も覚えていませんが解消しました ありがとうございます
