### ISSUE TITLE
node-oauthからrequestへの置換と書き換え

### ISSUE THREAD

**Issue by origamium** [tsuruclient/tsuru#13]
node-oauthはなぜか色々な部分で不完全だし、その不完全な部分をどうにかするためにかなりかったるい書き方をしていますし、streaming APIを呼ぶ際に私の脳が終了したので、よりシンプルな方のrequest/requestに置き換えようと思います。node-oauthどうして中途半端な状態なんでしょうね。

**Comment by FirstStar** [comment]
darui やらなくていいかな

**Comment by origamium** [comment]
この問題はtsuruclient/coreに移動されます。
