### ISSUE TITLE
Streaming APIへの対応と対応終了

### ISSUE THREAD

**Issue by origamium** [tsuruclient/tsuru#14]
はい

**Comment by FirstStar** [comment]
chunkを繋げるあたりでバグっており、JSON.parseが際限なく例外を吐いてしまうという問題で詰まっています  
恐らく最初のfriend listの受信あたりで早速バグっているのが悪くて、どうにかしなければならない…

**Comment by FirstStar** [comment]
実装が間違っていました 今はちゃんと実装できてます

**Comment by FirstStar** [comment]
今Twitterだけしか対応してないしhome timelineしか流さないし、謎のundefinedが流れてきたりもするのでなんとかしましょう

**Comment by FirstStar** [comment]
MastodonのStreaming APIでは各種イベントがEvent Stream Formatとして送信されてくるようです。また、接続維持のために定期的に`:thump`が降ってくる模様。空行が降ってくるTwitter Streaming APIよりは遥かにマシだとは思いますが…

**Comment by FirstStar** [comment]
`src/core/difference/api.js`に書いてあるStreaming APIの呼び出しですが、Mastodonはqueryにパラメータを書いてHomeかpublic/local timeilneか判別するようになっているようですし、Streaming APIはまたGET, POSTとは別の形式にしてもいいと思われる。

**Comment by FirstStar** [comment]
リプライ流れないことに気付いた

**Comment by FirstStar** [comment]
自分が発生させたFav & RTがNotificationに流れてしまうので、対応が必要

**Comment by FirstStar** [comment]
自分が発生させたFav & Rtを流さないように 01479eef8c8e564ea3451d613032417cab792ba7 で対応しました

**Comment by FirstStar** [comment]
Streaming API終了後のAccount Activity APIに対応する予定はありません。6月以後のTwitterへの対応は通常のREST APIのみとなります。

**Comment by origamium** [comment]
tsuruclient/coreにこの問題は移動されます。というか消えます。
