### ISSUE TITLE
APIを叩いてエラーが返されるとバグる

### ISSUE THREAD

**Issue by a-happin** [tsuruclient/tsuru#16]
例えば「空文字列を投稿する」などをしてAPIでエラーが返されると、「TLのUpdate」や「普通の投稿」などのAPIを利用する操作を行っても、何も起きなくなります。アプリケーションを再起動すれば直ります。

こちらの環境はArch Linux 64bitです。他の環境で再現するかはわかりませんが……。

**Comment by FirstStar** [comment]
原因わかりました、catchステートメント内で呼び出す関数をミスっていたため、さらにエラーが発生してredux-sagaが死んでいた模様です
