### ISSUE TITLE
連投バグ

### ISSUE THREAD

**Issue by a-happin** [tsuruclient/tsuru#17]
投稿ボックスに何か文字列を入れて送信ボタンをクリック連打すると連打した数だけ送信されます。
送信中は送信ボタンを押せないようにするなどの対処が必要と思われます。

**Comment by FirstStar** [comment]
送信ボタンを押したらFormを一旦全てクリック・編集不可にしてみます

**Comment by a-happin** [comment]
ん、クリックしたcolumn内だけでいいのでは……？

**Comment by FirstStar** [comment]
語弊があった column内のformをクリック・編集不可です
