### ISSUE TITLE
テストを書け

### ISSUE THREAD

**Issue by FirstStar** [tsuruclient/tsuru#20]
![dy2xt3rvaaamzjo_orig](https://user-images.githubusercontent.com/5967271/37788092-e72d8320-2e43-11e8-9fa4-e5051b3e69ad.jpg)

**Comment by origamium** [comment]
ビュー部分はJestでいけます

**Comment by origamium** [comment]
Travis CIでJestを実行+Jestのカバレッジレポートをcodecovで読ませる という態勢は一応できました

**Comment by origamium** [comment]
まあ コードカバレッジの0%をこのIssueの代わりとします
