### ISSUE TITLE
ビルドスクリプトの作成

### ISSUE THREAD

**Issue by FirstStar** [tsuruclient/tsuru#32]
electron-packagerで何も考えずビルドすると不要なファイルがぶちこまれてしまう上に、Windowsではelectron-packagerのignoreオプションが正常に使えないので、gulpなどのタスクランナーでビルドスクリプトを書いてあげましょう

**Comment by origamium** [comment]
書いたよ

**Comment by origamium** [comment]
結局素のNode.jsで書いたし、一体…
