### ISSUE TITLE
material-ui@nextの変更に追従する

### ISSUE THREAD

**Issue by origamium** [tsuruclient/tsuru#36]
しょっちゅう破壊的変更加わるので、なんかある度にここに追記します。

**Comment by FirstStar** [comment]
現在のところ
* Typographyの変更に伴う意図しない表示
* tooltipの変更によるaccount iconの意図しない表示
の2種類があります

**Comment by FirstStar** [comment]
Typographyに関してはすぐ対応できるものでした tooltipについては少し意味不明です

**Comment by origamium** [comment]
material-uiは安定版である1.0がリリースされました。Tsuru更新再開後に変更を適用します。
