### ISSUE TITLE
自動リリース化

### ISSUE THREAD

**Issue by FirstStar** [tsuruclient/tsuru#37]
現在Travis CIで自動リリースのテストをしています

**Comment by FirstStar** [comment]
Now working in progress with develop/build-script

**Comment by FirstStar** [comment]
やっていきをした結果とりあえず出るものは出るように、あとはtravis.yamlを書いていきましょう

**Comment by FirstStar** [comment]
Travis CIでまわしています https://travis-ci.org/tsuruclient/tsuru

**Comment by origamium** [comment]
タグつけたらビルドしてreleaseにまわすようにしてます いいですね
